######################
# Queue single assemblies with SPAdes with the metagenomic option  on WEI GLBRC
# Elizabeth McDaniel
######################

request_cpus = 16
request_memory = 400GB

executable = /home/GLBRCORG/emcdaniel/mcfaData/executables/auto_kmer_assembly.sh
arguments = $(sample) $(r1) $(r2)

output = /home/GLBRCORG/emcdaniel/mcfaData/outs/$(sample)_assemble.out
error = /home/GLBRCORG/emcdaniel/mcfaData/errs/$(sample)_assemble.err
log = /home/GLBRCORG/emcdaniel/mcfaData/logs/$(sample)_assemble.log

queue sample,r1,r2 from metadata/MCFA-assemblies-queue.txt
