##################
# fastp_filter.sub 
# Submission script for filtering metagenomic sequences with fastp
# Elizabeth McDaniel
##################

request_cpus = 4
request_memory = 50GB

executable = /home/GLBRCORG/emcdaniel/mcfaData/executables/fastp_filter.sh
arguments = $(sample) $(r1) $(r2) $(out1) $(out2)

output = /home/GLBRCORG/emcdaniel/mcfaData/outs/$(sample)_filter.out
error = /home/GLBRCORG/emcdaniel/mcfaData/errs/$(sample)_filter.err
log = /home/GLBRCORG/emcdaniel/mcfaData/logs/$(sample)_filter.log

queue sample,r1,r2,out1,out2 from metadata/filtering_queue_samples.txt
