##################
# metabat_binning.sub
# Submission script for binning on GLBRC with MetaBat
# Elizabeth McDaniel
##################

request_cpus = 4
request_memory = 5GB

executable = /home/GLBRCORG/emcdaniel/mcfaData/executables/binning-metabat.sh
arguments = $(ASSEMB)

output = /home/GLBRCORG/emcdaniel/mcfaData/outs/$(Cluster)_$(Process)_binning.out
error = /home/GLBRCORG/emcdaniel/mcfaData/errs/$(Cluster)_$(Process)_binning.err
log = /home/GLBRCORG/emcdaniel/mcfaData/logs/$(Cluster)_$(Process)_binning.log

queue ASSEMB from metadata/queue-MCFA-assembs-binning.txt
